ko_fi: tunnckoCore
patreon: tunnckoCore
tidelift: npm/formidable
github:
  - tunnckoCore
  
# Replace with up to 4 custom sponsorship URLs
custom:
  - https://gumroad.com/l/tunnckoCoreRecurringDonation
